---
version: '3.6'
services:
  xmas:
    image: "dallasmakerspace/ctf2018:latest"
    ports:
      - "8043/tcp"
    deploy:
      labels:
        orbiter.down: '3'
        orbiter.up: '6'
        orbiter: 'true'
        traefik.backend: 'northpole'
        traefik.default.protocol: 'http'
        traefik.enabled: 'true'
        traefik.frontend.entryPoints: 'http, https'
        traefik.frontend.priority: '10'
        traefik.frontend.rule: 'Host:northpole.dallasmakerspace.org'
        traefik.network: "public"
        traefik.docker.network: 'public'
        traefik.port: 8043
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      public: {}

networks:
  public:
    external: true
    name: public
...
