---
version: '3.6'
services:
  xmas:
    image: "dallasmakerspace/ctf2018:latest"
    ports:
      - "8043/tcp"
    deploy:
      labels:
        traefik.port: 8043
        traefik.network: "public"
        traefik.enabled: 'true'
        traefik.frontend.priority: "10"
        traefik.frontend.rules: 'Host: northpole.dallasmakerspace.org'
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      public: {}

networks:
  public:
    external: true
    name: public
...
